baseURL = "https://johntzulik.netlify.app"
disqusShortname = ""
googleAnalytics = ""
paginate = "3"
summaryLength = "15"
theme = "bigspring"
title = "Juan Felipe Morales"
[markup.goldmark.renderer]
unsafe = true
