[[footer_left]]
name = "Acerca de"
url = "#"
[[footer_left]]
name = "Inicio rápido"
url = "#"
[[footer_left]]
name = "Precio"
url = "pricing"
[[footer_middle]]
name = "Precio"
url = "pricing"
[[footer_middle]]
name = "Plataforma"
url = "#"
[[footer_middle]]
name = "Caracteristicas"
url = "#"
[[footer_right]]
name = "Politica de privacidad"
url = "privacy-policy"
[[footer_right]]
name = "Terminos y condiciones"
url = "terms-conditions"
[[footer_right]]
name = "FAQ"
url = "faq"
[[main]]
name = "Inicio"
url = "/"
weight = 1
[[main]]
name = "Blog"
url = "blog"
weight = 2
[[main]]
name = "Contacto"
url = "contact"
weight = 4
[[main]]
name = "CV"
url = "cv"
weight = 5
